spring.application.name=eron

eternal-return.api.base-url=https://open-api.bser.io/v1
eternal-return.api.key=${ER_API_KEY:}
eternal-return.api.connect-timeout=3s
eternal-return.api.read-timeout=10s
eternal-return.api.user-games-cache-ttl=30s
